const questions = [
  "Do you prefer working remotely or working in an office?",
  "Is there a spot in your house where you feel most productive?",
  "If you could have any upgrade to your WorkFromHome setup, what would it be?",
  "What’s your morning routine?",
  "How often do you work in pajama?",
  "Who’s the most famous person you’ve ever met? Tell the story of how you met.",
  "What’s your guilty pleasure?",
  "Looking back at when you were younger, what was your silliest fear?",
  "What is your current desktop or cell phone wallpaper? Why did you choose that image?",
  "Tell about your worst hair day.",
  "If you had to give your car a name, what would it be?",
  "What’s your favorite silly joke?",
  "If you could choose to host a talk show, which one would you pick?",
  "What was your best Halloween costume? Worst?",
  "Tell us a story of an embarrassing thing that happened to you.",
  "What’s the last thing you got in “trouble” for?",
  "What would the title of your autobiography be?",
  "If you could add a word to the dictionary, what would you add and what would it mean?",
  "If you could bring back any fashion trend or old slang, what would it be?",
  "If you had to talk like a cartoon character for the rest of your life, who would you choose? Do an impression of them now.",
  "What’s the worst piece of advice you’ve ever been given?",
  "If you had to eat a crayon, what color would you choose?",
  "Where did you grow up?",
  "Did you have any pets as a kid? Did you want any pets?",
  "Did you play sports as a kid? Do you play any sports now?",
  "Do you speak any other languages?",
  "What’s your favorite place in the world?",
  "What was your first job?",
  "What was your favorite cartoon as a kid? What was your favorite cartoon character? If they weren’t the same, why not?",
  "Who in life has inspired you the most?",
  "What’s one family tradition you want to pass down to your kids?",
  "What’s a piece of advice your parents or grandparents gave you that you want to pass on?",
  "What were your favorite subjects in school?",
  "Did you have an imaginary friend when you were younger? What were they like?",
  "Have you ever been mistaken for someone famous?",
  "What book are you currently reading? What’s your favorite book?",
  "What’s your favorite series?",
  "What’s your favorite movie?",
  "What’s your favorite song?",
  "What was your first concert? What was the best concert you’ve ever been to?",
  "If you were stranded on a deserted island, what book or object would you bring?",
  "If you could have dinner with one historical figure, who would it be?",
  "What’s the greatest gift you’ve ever received? What about the best gift you’ve ever given?",
  "Do you have any hidden talents?",
  "When you were younger, what did you want to be when you grew up?",
  "If you were granted three wishes, what would you wish for?",
  "If you won a million dollars, what’s the first thing you’d do?",
  "What are you passionate about outside of work?",
  "If you had an extra hour per day, what would you do?",
  "Are you a dog person, a cat person, or both?",
  "What game show do you think you could win?",
  "If you could only use one emoji for the rest of your life what would it be?",
  "What’s something you think is totally overrated?",
  "If you were an athlete, what would you choose as your walkout song?",
  "What book do you wish you could read for the first time again?",
  "Name one movie you think should have a sequel.",
  "What was the first thing you thought about this morning?",
  "What has been the best day of your life so far?",
  "If aliens landed on Earth, who would you recommend they talk to?",
  "What’s your favorite place in the world?",
  "Have you ever traveled outside of the country?",
  "Mountains or ocean?",
  "Snow or sand?",
  "Where did you go the first time you traveled (or remember traveling)?",
  "What is your favorite thing to do locally?",
  "If you had to move to another country, where would you move?",
  "What’s your favorite food?",
  "What is your favorite pizza?",
  "What’s your favorite drink?",
  "If you could name a cocktail, what would you call it?",
  "Spicy or sweet?",
  "What is your favorite fast food restaurant?",
  "Was there ever a food you didn’t want to eat, but you loved it once you tried it?",
  "Would you rather go on a beach vacation or a travel adventure vacation?",
  "Would you rather be a member of the Avengers or the Justice League?",
  "Would you rather have a theme song for your life or a constant soundtrack playing in the background?",
  "Would you rather be a superhero or the world’s best chef?",
  "Would you rather sing karaoke with the head of our department or be on a group call with the CEO and your parents?",
  "If you had to live in a video game, which one would it be?",
  "If you could have any superpower, what would it be?",
  "If you could remove one word from the dictionary, what would it be?",
  "If you could be any animal, which would you be?",
  "If you could control one element (air, water, earth, fire), which would it be and why?",
  "If you had to live in one Disney movie, which would you choose?",
  "If you could send a message out to the entire world, what would it be?",
  "If you could only watch one movie for the rest of your life, what would it be?",
  "If you could only listen to one album for the rest of your life, which would you choose?",
  "If you were a potato, how would you like to be cooked?",
  "You have 20 minutes to plan for the zombie apocalypse—what do you do? What if you had 24 hours?",
  "What’s something you’ve always wanted to do but haven’t done yet? Why not?",
  "When was the last time you did something for the first time?",
  "What do you do to beat stress?",
  "What’s the most surprising thing that’s happened to you in another country?",
  "Tell something about yourself that would surprise most people who know you.",
  "Describe an experience in life that changed your values.",
  "What’s the hardest part about working virtually for you? The easiest?",
  "Do you have a dedicated office space at home?",
  "Show your office space!",
  "Where do you work most frequently from at home? Your office? Your kitchen table? The backyard? Your bed?",
  "Be honest, how often do you work from bed?",
  "What’s your number one tip for combating distractions when working from home?",
  "What’s your favorite flower or plant?",
  "Best professional development book you’ve ever read?",
  "If you could learn one new professional skill, what would it be?",
  "If you could learn one new personal skill, what would it be?",
  "What’s your favorite way to get in some exercise?",
  "If you could write a book, what genre would you write it in?",
  "The zombie apocalypse is coming, who are 3 people you want on your team?",
  "What was the worst style choice you ever made?",
  "Who was your childhood actor/actress crush?",
  "If you were a wrestler what would be your entrance theme song?",
  "Have you ever been told you look like someone famous, who was it?",
  "If you could bring back any fashion trend what would it be?",
  "What’s the most embarrassing fashion trend you used to rock?",
  "You have your own late night talk show, who do you invite as your first guest?",
  "If a movie was made of your life what genre would it be, who would play you?",
  "If you were famous, what would you be famous for?",
  "What was your least favorite food as a child? Do you still hate it or do you love it now?",
  "If you had to eat one meal everyday for the rest of your life what would it be?",
  "If you were left on a deserted island with either your worst enemy or no one, which would you choose? Why?",
  "If aliens landed on earth tomorrow and offered to take you home with them, would you go?",
  "60s, 70s, 80s, 90s: Which decade do you love the most and why?",
  "What’s the best piece of advice you’ve ever been given?",
  "What is your favorite item you’ve bought this year?",
  "What would be the most surprising scientific discovery imaginable?",
  "What is your absolute dream job?",
  "Say you’re independently wealthy and don’t have to work, what would you do with your time?",
  "If you had to delete all but 3 apps from your smartphone, which ones would you keep?",
  "What does your favorite shirt look like?",
  "What would your dream house be like?",
  "You’re going sail around the world, what’s the name of your boat?",
  "What fictional family would you be a member of?",
  "Who is the better businessman or business woman and why? (Example: Justin Timberlake or Justin Bieber?)",
  "What was the worst job you ever had?",
  "You can have anyone fictional as your imaginary friend, who do you choose and why?",
  "What’s your favorite tradition or holiday?",
  "What fictional world or place would you like to visit?",
  "What is your favorite breakfast food?",
  "What is your favorite time of the day and why?",
  "Teleportation or flying?",
  "What book, movie read/seen recently you would recommend and why?",
  "If you had a time machine, would go back in time or into the future?",
  "What was your favorite game to play as a child?",
  "Are you a traveler or a homebody?",
  "What’s one career you wish you could have?",
  "What fictional world or place would you like to visit?",
  "What’s your favorite place of all the places you’ve travelled?",
  "What is your favorite meal to cook and why?",
  "What is your favorite musical instrument and why?",
  "Popcorn or M&Ms?",
  "What’s the weirdest food you’ve ever eaten?",
  "What’s the most out-of-character thing you’ve ever done?",
  "What is your cellphone wallpaper?",
  "You can have an unlimited supply of one thing for the rest of your life, what is it? Sushi? Scotch Tape?",
  "What’s your best scar story?",
  "Would you go with aliens if they beamed down to Earth?",
  "Are you a good dancer?",
  "What fruit or vegetable would you most want to be?",
  "If you could live anywhere in the world for a year, where would it be?",
  "If you could commit any crime and get away with it what would you choose and why?",
  "If you could choose any person from history to be your imaginary friend, who would it be and why?",
  "If you could see one movie again for the first time, what would it be and why?",
  "If you could be any animal in the world, what animal would you choose to be?",
  "If you could do anything in the world as your career, what would you do?",
  "If you could be any supernatural creature, what would you be and why?",
  "If you could rename yourself, what name would you pick?",
  "If you could have someone follow you around all the time, like a personal assistant, what would you have them do?",
  "If you could instantly become an expert in something, what would it be?",
  "If you could be guaranteed one thing in life (besides money), what would it be?",
  "If you had to teach someone on one thing, what would you teach?",
  "If you could be immortal, what age would you choose to stop aging at and why?",
  "If you could eliminate one thing from your daily routine, what would it be and why?",
  "If you could go to Mars, would you? Why or why not?",
  "If you could have the power of teleportation right now, where would you go and why?",
  "Would you rather live in the ocean or on the moon?",
  "Would you rather meet your travel back in time to meet your ancestors or to the future to meet your descendants?",
  "Would you rather lose all of your money or all of your pictures?",
  "Would you rather have invisibility or flight?",
  "Would you rather live where it only snows or only warm?",
  "Would you rather give up your smartphone or your computer?",
  "Would you rather be the funniest or smartest person in the room?",
  "Would you rather be an Olympic gold medallist or an astronaut?",
  "Would you rather be reincarnated as a cat or a dog?",
  "If you could try any food, what would it be?",
  "You are stranded on a remote desert island. Are you alone or with your worst enemy?",
  "What is the best thing you have bought so far this year?",
  "What superpower would you most want?",
  "Show us the weirdest thing you have in the room with you right now.",
  "Who is your favorite author?",
  "What is your favorite holiday?",
  "What is your favorite book genre to read?",
  "What is your favorite movie genre to watch?",
  "What is your most used phone app?",
  "What is something people would not know about you just by looking?",
  "What is your #1 recommendation in your city?",
  "What is your favorite kitchen gadget?",
  "You can visit any fictional time or place. Which would you pick?",
  "What was your favorite show as a kid?",
  "What is the earliest book you remember?",
  "What is your favorite season?",
  "Imagine you no longer have to work. How would you spend a Tuesday?",
  "What is your favorite holiday tradition?",
  "What would it take to give up your smartphone for a month?",
  "What is your favorite dessert?",
  "Where is your favorite vacation spot?",
  "What food will you never eat?",
  "Would you rather have a pet sloth or a pet parrot?",
  "Which movie made you laugh the most?",
  "Have you ever been to a comedy show?",
  "What is the best romantic comedy?",
  "What is the most obscure superpower you would want? Which superpower would you give to your arch enemy?",
  "How would you rate your laugh out of 10?",
  "What is the strangest food you have tried? Would you eat it again?",
  "What vegetable is best with cheese?",
  "There is a free, round-trip shuttle to Mars. The catch: it will take one year of your life to go, visit, and come back. Are you in?",
  "Imagine you could teleport anywhere. Where would you go right now?",
  "Pick any band to play at your funeral.",
  "What was your first job?",
  "What is the most unusual job you have heard of?",
  "Would it be better to start work five years later or end five years earlier?",
  "What is something you did at work that no-one noticed?",
  "Which fictional team is the best team of all time?",
  "Would you rather join Metallica or Backstreet Boys?",
  "What was the first team you were part of?",
  "Have you ever won something as a team?",
  "Would you rather do a large project independently or as part of a team?",
  "What is a good way to give back to the community?",
  "What is an easy way to do something nice for someone?",
  "Who is someone in your community that makes a difference?",
  "Would you rather live in a city or a town?",
  "What is the best example of a community you have seen?",
  "Would you join a community in space if it was permanent?",
  "Would you rather live 100 years in the past or 100 years in the future?",
  "What is the first gift you remember receiving?",
  "What is your earliest memory of Christmas?",
  "Have you ever told someone Santa is not real?",
  "What is the best holiday treat?",
  "What is a holiday tradition you like?",
  "What is your New Years resolution?",
  "Would you rather live at the North Pole or in Africa?",
];
(function () {
  const max = questions.length;
  const index = Math.floor(Math.random() * max);
  const questionPlaceholder = document.getElementById("question-placeholder");

  questionPlaceholder.innerText = questions[index];
})();
